prerequisites_packages:
- "gnupg"
- "apt-transport-https" 
- "dnsutils"
- "curl"
- "net-tools"

faucet_packages:
- "faucet-all-in-one"


# prometheus default vars
scrapeinterval: 30s
evaluationinterval: 15s


