prerequisites_packages:
- "gnupg"
- "apt-transport-https" 
- "dnsutils"
- "curl"
- "net-tools"

faucet_packages:
- "faucet-all-in-one"


####
# Grafana vars
grafana_port: 3000
grafana_user: admin
grafana_password: admin
grafana_plugins: 
 - prometheus
grafana_datasource: {
        isDefault: yes,
        name: prometheus,
        type: prometheus,
        access: proxy,
        url: 'http://localhost:9090'
      }

# prometheus default vars
scrapeinterval: 30s
evaluationinterval: 15s


